-- Role: "FLEET_MANAGER"
-- DROP ROLE IF EXISTS "FLEET_MANAGER";

CREATE ROLE "FLEET_MANAGER" WITH
  LOGIN
  NOSUPERUSER
  NOINHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION
  ENCRYPTED PASSWORD 'SCRAM-SHA-256$4096:eDgU99YEVKy1y/IMO4HWKQ==$f1C+qpj+I+Q9AY6IuFvynySZJEN42NUvdIaCTMuQP9g=:THj4xhu/Cla22RFNVqlmE6LZcSEvtLQvn1+SB13Sk1A=';