-- Role: "HR_MANAGER"
-- DROP ROLE IF EXISTS "HR_MANAGER";

CREATE ROLE "HR_MANAGER" WITH
  LOGIN
  NOSUPERUSER
  NOINHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION
  ENCRYPTED PASSWORD 'SCRAM-SHA-256$4096:m10J7505Z+IbCH4wJ7OT+w==$SlT9E47mgTQuwZ/hsh0RRv3s6V9pG+KMneN4YPtIEpM=:gXhtlio6F4wvDDwVtAMAYZ/fl5LBWkT1ntE/9bV0M8Q=';