-- Role: "LEASING_MANAGER"
-- DROP ROLE IF EXISTS "LEASING_MANAGER";

CREATE ROLE "LEASING_MANAGER" WITH
  LOGIN
  NOSUPERUSER
  NOINHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION
  ENCRYPTED PASSWORD 'SCRAM-SHA-256$4096:II7jEVCcCwFE27aim4E5eA==$mFCVa/WvWnRBmdza6vsjmViMSl07b32IclqhrwHkk5Q=:o97gohq3PbiG0A9vrGlNbCd8sVX6jkjJeNSbvbg+71Q=';